### PR TITLE
Edit Markdown instead of raw XML

### PR DESCRIPTION
**Pull request by cjpatton**
This obsoletes #11.

My name is Chris Patton. I'm a PhD student in cryptography. I have an idea for a paper and am interested in using the standardization of SPAKE2 as a case study. I'd like to recommend a few changes to the spec, and @wbl indicated that you two would be able to review them. I plan to make a PR consisting of these recommendations soon.

First, I've taken the liberty of converting the XML source into Markdown, which, AFAIK, is now the de facto means of typesetting RFCs (e.g., [TLS 1.3](https://github.com/tlswg/tls13-spec/blob/master/draft-ietf-tls-tls13.md)). This should be far easier than editing raw XML.

The source was `draft-irtf-spake2.xml` and is now `draft-irtf-cfrg-spake2.md`.

### CODE REVIEW

**Comment by kaduk** [comment]
> converting the XML source into Markdown, which, AFAIK, is now the de facto means of typesetting RFCs (e.g., TLS 1.3). This should be far easier than editing raw XML.

FWIW, your knowledge is incomplete in this regard -- while many people use markdown and have a great experience, it's by no means required or universally used.  Some people write raw XML, and I believe some 10% of RFCs started life using an MS Word template (and went through a pure-text intermediate version).  I'll wait for Watson to say what his preferences are, but I personally am more comfortable with the raw XML than with Markdown.  (That said, I'm not allergic to Markdown, and submit patches to many documents that are written in it without any particular issue; it's just a matter of preference.)

**Comment by cjpatton** [comment]
Sounds good. My experience has been that it's easier to keep PRs minimal with Markdown, but obviously it's not my call.

**Comment by wbl** [comment]
I'm fine with XML and Benjamin prefers it, so let's keep it in XML.

**Comment by cjpatton** [comment]
Alrighty, closing.

**Pull request closed without merging**
